---

- name: Verify
  hosts: molecule_hosts
  gather_facts: yes
  become: yes
  tasks:
    - name: Assert logical volume is correct
      ansible.builtin.assert:
        that:
          - ansible_facts.lvm.lvs.lv is defined
          - ansible_facts.lvm.lvs.lv.size_g == "0.50"
